# Generated by Django 4.0.8 on 2023-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.UUIDField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('travel_medium', models.CharField(choices=[('BS', 'BUS'), ('TR', 'TRAIN'), ('CR', 'CAR')], max_length=2)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Rider',
            },
        ),
    ]
