# Generated by Django 4.0.8 on 2023-01-24 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='rider_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
