# Generated by Django 4.0.8 on 2023-01-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0002_alter_rider_rider_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='date',
            new_name='datetime',
        ),
    ]
