# Generated by Django 4.0.8 on 2023-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0003_rename_date_rider_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
