# Generated by Django 4.0.8 on 2023-01-24 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('quantity', models.IntegerField(default=1)),
                ('asset_type', models.CharField(choices=[('LP', 'LAPTOP'), ('TB', 'TRAVEL_BAG'), ('PK', 'PACKAGE')], max_length=2)),
                ('sensitivity', models.CharField(choices=[('HS', 'HIGHLY_SENSITIVE'), ('S', 'SENSITIVE'), ('N', 'NORMAL')], max_length=2)),
                ('status', models.CharField(choices=[('PD', 'PENDING'), ('EX', 'EXPIRED')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('requester_id', models.IntegerField(db_index=True, max_length=3)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requester_app.request')),
            ],
        ),
    ]
