# Generated by Django 4.0.8 on 2023-01-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('EX', 'EXPIRED')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='requester',
            name='requester_id',
            field=models.IntegerField(),
        ),
    ]
