# Generated by Django 4.0.8 on 2023-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester_app', '0002_alter_request_status_alter_requester_requester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
