# Generated by Django 4.0.8 on 2023-01-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0004_rider_timestamp'),
        ('requester_app', '0003_request_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requester_app.requester')),
                ('rider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
        ),
    ]
